### ISSUE TITLE
bigquery root element

### ISSUE THREAD

**Issue by JacobSMoller** [einride/protobuf-avro-go#67]
Hi nice little project you have here. 

I just ran your example and tried loading it in to bigquery. The way the OCF is written bigquery adds a `root` column and nests the book data under that - is this intended or is there a way to write the OCF in a way that doesn't add a `root`
<img width="664" alt="Screenshot 2022-08-11 at 09 38 21" src="https://user-images.githubusercontent.com/13047162/184088077-7e721e4c-83c5-4909-8fdc-62950d8798b7.png">

**Comment by ericwenn** [comment]
Hello @JacobSMoller 

The root column is as far as I can tell something that can not be removed when using avro to import into BigQuery.
The way we have this configured is to "spread" the root column as a first step in BigQuery, like this:
```sql
SELECT root.* FROM my_table
```

That will give you columns that map to your protobuf messages.

**Comment by JacobSMoller** [comment]
Hello @ericwenn  thanks for the response. 

I know its possible to write avro to bigquery without root.
You can try with this for example
```
bq load --source_format=AVRO --project_id some-project dataset.table gs://cloud-samples-data/bigquery/us-states/us-states.avro
```

**Comment by ericwenn** [comment]
> Hello @ericwenn thanks for the response.
> 
> I know its possible to write avro to bigquery without root. You can try with this for example
> 
> ```
> bq load --source_format=AVRO --project_id some-project dataset.table gs://cloud-samples-data/bigquery/us-states/us-states.avro
> ```
> 
> But if it doesn't fit your use case we will try to solve that issue on our end and see if we can do it in way we can contribute back to this repo :)

Oh, didn't know!
Was some time since we built this, but as I remember it, it was not able to get it to omit the `root` column.  But maybe we just didn't try hard enough :)

**Comment by JacobSMoller** [comment]
All good we found a way to make it work. 

Will see if we can wrap it in a PR that can be contributed back here without breaking stuff :)

**Comment by ericwenn** [comment]
> All good we found a way to make it work.
> 
> Will see if we can wrap it in a PR that can be contributed back here without breaking stuff :)

If it is a breaking change we can add an schema option for it, similar to what we are doing in a related library here https://github.com/einride/protobuf-bigquery-go/blob/master/encoding/protobq/schema.go#L15-L38
